# Generated by Django 6.0.3 on 2026-04-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loges', '0006_loge_rite_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCouverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tenue', models.DateField()),
                ('nombre_couverts', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('email_contact', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('non_lu', 'Non lue'), ('lu', 'Lue')], default='non_lu', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_couverts', to='loges.loge')),
            ],
            options={
                'verbose_name': 'Notification couverts',
                'verbose_name_plural': 'Notifications couverts',
                'ordering': ['-created_at'],
            },
        ),
    ]
