# Generated by Django 5.0.6 on 2026-03-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obedience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Obédience',
                'verbose_name_plural': 'Obédiences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Loge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('abréviation', models.CharField(blank=True, max_length=20)),
                ('type_loge', models.CharField(choices=[('loge', 'Loge'), ('haut_grade', 'Haut Grade')], default='loge', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('effectif_total', models.PositiveIntegerField(default=0)),
                ('effectif_moyen_agapes', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obedience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loges', to='loges.obedience')),
            ],
            options={
                'verbose_name': 'Loge',
                'verbose_name_plural': 'Loges',
                'ordering': ['nom'],
            },
        ),
    ]
