# Generated by Django 5.0.6 on 2026-03-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loge',
            old_name='abréviation',
            new_name='abreviation',
        ),
    ]
