# Generated by Django 5.0.6 on 2026-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0002_rename_abréviation_loge_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loge',
            name='rite',
            field=models.CharField(blank=True, choices=[('reaa', 'REAA — Rite Écossais Ancien et Accepté'), ('rer', 'RER — Rite Écossais Rectifié'), ('rf', 'RF — Rite Français'), ('rem', 'REM — Rite Écossais Moderne'), ('dh', 'DH — Droit Humain'), ('mem', 'MEM — Memphis-Misraïm'), ('autre', 'Autre')], default='', max_length=10),
        ),
    ]
