# Generated by Django 6.0.3 on 2026-04-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0004_rite_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loge',
            name='rite',
            field=models.CharField(blank=True, choices=[('reaa', 'REAA — Rite Écossais Ancien et Accepté'), ('rer', 'RER — Rite Écossais Rectifié'), ('rf', 'RF — Rite Français'), ('rf_reaa', 'RF/REAA — Rite Français et Rite Écossais Ancien et Accepté'), ('rem', 'REM — Rite Écossais Moderne'), ('dh', 'DH — Droit Humain'), ('mem', 'MEM — Memphis-Misraïm'), ('rapmm', 'RAPMM — Rite Ancien et Primitif de Memphis-Misraïm'), ('rmfr', 'RMFR — Rite Moderne Français Rectifié'), ('emulation', 'Emulation'), ('marque', 'Marque et York'), ('autre', 'Autre')], default='', max_length=20),
        ),
    ]
