# Generated by Django 6.0.3 on 2026-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0006_loge_rite_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='loge',
            name='nom_contact',
            field=models.CharField(blank=True, default='', help_text='Nom du contact / vénérable', max_length=200),
        ),
        migrations.AddField(
            model_name='loge',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
