# Generated by Django 6.0.3 on 2026-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0007_loge_nom_contact_loge_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loge',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('a_reconfirmer', 'À reconfirmer'), ('inactive', 'Inactive')], default='active', help_text='Active = confirmée ; À reconfirmer = pas de retour pour la nouvelle saison ; Inactive = dissoute/partie', max_length=15),
        ),
    ]
