# Generated by Django 6.0.3 on 2026-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0009_loge_statut_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='loge',
            name='association',
            field=models.CharField(blank=True, default='', help_text="Nom d'association / atelier complémentaire (ex. « P46 - La Sagesse »)", max_length=200),
        ),
    ]
