# Generated by Django 5.0.6 on 2026-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loges", "0010_loge_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="loge",
            name="couverts_habituels",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre de couverts habituels renseigné par le traiteur (prioritaire sur effectif_moyen_agapes)",
                null=True,
            ),
        ),
    ]
