# Generated by Django 6.0.3 on 2026-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_de_passe_annuel', models.CharField(default='KELLERMANN2026', max_length=100)),
                ('email_admin', models.EmailField(max_length=254)),
                ('email_from', models.EmailField(default='noreply@temple-reservations.fr', max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
