# Generated by Django 6.0.3 on 2026-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_journalevenement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalevenement',
            new_name='administrat_date_he_faa359_idx',
            old_name='admin_journal_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalevenement',
            new_name='administrat_type_ev_28d79b_idx',
            old_name='admin_journal_type_idx',
        ),
        migrations.RenameIndex(
            model_name='journalevenement',
            new_name='administrat_objet_t_9d7937_idx',
            old_name='admin_journal_objet_idx',
        ),
        migrations.AlterField(
            model_name='journalevenement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalevenement',
            name='type_evenement',
            field=models.CharField(choices=[('validation_reservation', 'Validation réservation'), ('refus_reservation', 'Refus réservation'), ('modification_reservation', 'Modification réservation'), ('soumission_portail_loge', 'Soumission portail loge'), ('ouverture_validation_saison', 'Ouverture validation saison'), ('envoi_emails_saison', 'Envoi emails saison'), ('soumission_validation_loge', 'Soumission validation loge'), ('import_excel', 'Import Excel'), ('backup_base', 'Backup base de données'), ('creation_reservation_directe', 'Création réservation directe'), ('creation_acces_portail', 'Création accès portail'), ('envoi_lien_portail', 'Envoi lien portail')], db_index=True, max_length=40),
        ),
    ]
