# Generated by Django 6.0.3 on 2026-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_journalevenement_add_portail_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Texte affiché dans le pop-up. Les retours à la ligne sont conservés.')),
                ('niveau', models.CharField(choices=[('info', 'Information (bleu)'), ('success', 'Succès (vert)'), ('warning', 'Avertissement (orange)'), ('danger', 'Important (rouge)')], default='info', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(blank=True, help_text='Début de diffusion (laisser vide = immédiat)', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin de diffusion (laisser vide = sans limite)', null=True)),
                ('duree_affichage', models.PositiveIntegerField(default=0, help_text="Fermeture automatique après X secondes (0 = jusqu'à fermeture manuelle)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonce / Pop-up',
                'verbose_name_plural': 'Annonces / Pop-ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
