# Generated by Django 6.0.3 on 2026-06-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='tarif_congres_jour',
            field=models.DecimalField(decimal_places=2, default=300, help_text='Congrès / session régionale, par jour (€)', max_digits=8),
        ),
        migrations.AddField(
            model_name='parametres',
            name='tarif_exc_avec_agapes',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Occupation exceptionnelle avec agapes (€)', max_digits=8),
        ),
        migrations.AddField(
            model_name='parametres',
            name='tarif_exc_sans_agapes',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Occupation exceptionnelle sans agapes (€)', max_digits=8),
        ),
    ]
