# Generated by Django 6.0.3 on 2026-06-17 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_parametres_tarif_congres_jour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='tarif_date_effet',
            field=models.DateField(blank=True, default=datetime.date(2026, 6, 12), help_text="Date d'entrée en vigueur des tarifs (vote AG). Les occupations antérieures ne sont pas facturées.", null=True),
        ),
    ]
