# Generated by Django 6.0.3 on 2026-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_init_tarifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='tarif_funebre',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Tenue funèbre exceptionnelle (week-end / vacances) (€)', max_digits=8),
        ),
    ]
