# Generated by Django 6.0.3 on 2026-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_parametres_tarif_funebre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='facturation_active',
            field=models.BooleanField(default=True, help_text="Active la facturation des occupations. À désactiver tant que le modèle n'est pas validé avec le trésorier."),
        ),
    ]
