# Generated by Django 6.0.3 on 2026-07-09 09:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_parametres_facturation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='tarif_membre_hg',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.80'), help_text='Redevance par membre pour un haut grade (€).', max_digits=8),
        ),
        migrations.AddField(
            model_name='parametres',
            name='tarif_membre_loge',
            field=models.DecimalField(decimal_places=2, default=85, help_text='Redevance par membre pour une loge bleue (€).', max_digits=8),
        ),
    ]
