# Generated by Django 5.0.6 on 2026-09-19 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0019_fix_facture_bigautofield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaTarification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "saison",
                    models.PositiveSmallIntegerField(
                        help_text="Année de début de saison (ex : 2026 pour 2026-2027)"
                    ),
                ),
                ("date_effet", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("simule", "Simulé"), ("vote", "Voté en AG")],
                        default="simule",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("membre", "Par membre"),
                            ("hybride", "Hybride (membre + tenue)"),
                        ],
                        default="membre",
                        max_length=10,
                    ),
                ),
                (
                    "tarif_membre_loge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_membre_hg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_tenue_lb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_tenue_hg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_exc_sans_agapes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_exc_avec_agapes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_congres_jour",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_funebre",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "tarif_minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum de cotisation par structure (€, optionnel)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "plafond_hausse_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Plafond de hausse par rapport au tarif précédent (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schemas_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schéma de tarification",
                "verbose_name_plural": "Schémas de tarification",
                "ordering": ["-saison", "-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="DecisionAG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saison",
                    models.PositiveSmallIntegerField(
                        help_text="Saison concernée (ex : 2026 pour 2026-2027)"
                    ),
                ),
                ("date_ag", models.DateField()),
                (
                    "libelle_resolution",
                    models.CharField(
                        help_text="Titre ou numéro de résolution", max_length=500
                    ),
                ),
                (
                    "pv",
                    models.FileField(
                        blank=True,
                        help_text="Procès-verbal de l'AG (PDF)",
                        null=True,
                        upload_to="pv_ag/",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("votee", "Votée")],
                        default="brouillon",
                        max_length=10,
                    ),
                ),
                (
                    "budget_energie",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_fluides",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_consommables",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_entretien",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_maintenance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_assurances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_services_ext",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_impots",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_personnel",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "budget_amortissements",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_ag_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_ag",
                        to="administration.schematarification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Décision d'AG",
                "verbose_name_plural": "Décisions d'AG",
                "ordering": ["-saison", "-date_ag"],
            },
        ),
        migrations.AddField(
            model_name="facture",
            name="schema_applique",
            field=models.ForeignKey(
                blank=True,
                help_text="Schéma de tarification utilisé pour générer cette facture",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factures",
                to="administration.schematarification",
            ),
        ),
        migrations.AddField(
            model_name="parametres",
            name="schema_actif",
            field=models.ForeignKey(
                blank=True,
                help_text="Schéma de tarification voté en AG et actuellement en vigueur.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="administration.schematarification",
            ),
        ),
    ]
