# Generated by Django 5.0.6 on 2026-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0020_ag_schema_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignefacture",
            name="note_override",
            field=models.CharField(
                blank=True,
                help_text="Motif de la correction manuelle du tarif (ex: cuisine partagée)",
                max_length=300,
            ),
        ),
    ]
