# Generated by Django 5.0.6 on 2026-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0021_ligne_facture_note_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametres",
            name="effectif_par_defaut",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Effectif utilisé (en estimation) pour le calcul des cotisations quand la fiche loge n'a pas encore d'effectif saisi.",
            ),
        ),
    ]
