# Generated by Django 5.0.6 on 2026-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0022_parametres_effectif_defaut"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametres",
            name="modele_cotisation",
            field=models.CharField(
                choices=[
                    ("B", "Cas B — €/membre (tarif fixe annuel)"),
                    ("A", "Cas A — €/membre/tenue (tarif proportionnel à l'activité)"),
                ],
                default="B",
                help_text="Cas B = cotisation fixe par membre. Cas A = tarif × effectif × nb_tenues par loge (reflète l'utilisation réelle).",
                max_length=1,
            ),
        ),
    ]
