# Generated by Django 5.0.6 on 2026-03-27 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Cabinet de réflexion',
                'verbose_name_plural': 'Cabinets de réflexion',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('lafayette', 'Temple Lafayette'), ('liberte', 'Temple Liberté'), ('egalite', 'Temple Égalité'), ('fraternite', 'Temple Fraternité')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Temple',
                'verbose_name_plural': 'Temples',
            },
        ),
        migrations.CreateModel(
            name='RegleRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('numero_semaine', models.SmallIntegerField(choices=[(1, '1re semaine'), (2, '2e semaine'), (3, '3e semaine'), (4, '4e semaine'), (-1, 'Dernière semaine')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('loge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='loges.loge')),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.temple')),
            ],
            options={
                'verbose_name': 'Règle de récurrence',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_reservation', models.CharField(choices=[('reguliere', 'Régulière'), ('exceptionnelle', 'Exceptionnelle')], default='reguliere', max_length=20)),
                ('sous_type', models.CharField(choices=[('standard', 'Standard'), ('tbf', 'Tenue Blanche Fermée'), ('tbo', 'Tenue Blanche Ouverte')], default='standard', max_length=10)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='attente', max_length=20)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('besoin_agapes', models.BooleanField(default=False)),
                ('nombre_repas', models.PositiveIntegerField(default=0)),
                ('besoin_micro', models.BooleanField(default=False)),
                ('besoin_enceintes', models.BooleanField(default=False)),
                ('nom_demandeur', models.CharField(max_length=200)),
                ('email_demandeur', models.EmailField(max_length=254)),
                ('commentaire', models.TextField(blank=True)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinets', models.ManyToManyField(blank=True, to='reservations.cabinet')),
                ('loge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='loges.loge')),
                ('regle_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reglerecurrence')),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.temple')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('temples', models.ManyToManyField(blank=True, related_name='indisponibilites', to='reservations.temple')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
                'verbose_name_plural': 'Indisponibilités',
                'ordering': ['date_debut'],
            },
        ),
    ]
