# Generated by Django 5.0.6 on 2026-03-28 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle de réunion',
                'verbose_name_plural': 'Salles de réunion',
                'ordering': ['capacite', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='reglerecurrence',
            options={'verbose_name': 'Règle de récurrence', 'verbose_name_plural': 'Règles de récurrence'},
        ),
        migrations.AddField(
            model_name='reglerecurrence',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Début de validité (laisser vide = début de saison sept.)', null=True),
        ),
        migrations.AddField(
            model_name='reglerecurrence',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Fin de validité (laisser vide = fin de saison juin)', null=True),
        ),
        migrations.AlterField(
            model_name='reglerecurrence',
            name='heure_debut',
            field=models.TimeField(default='19:30'),
        ),
        migrations.AlterField(
            model_name='reglerecurrence',
            name='heure_fin',
            field=models.TimeField(default='22:30'),
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='attente', max_length=20)),
                ('nom_demandeur', models.CharField(max_length=200)),
                ('email_demandeur', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, help_text='Loge, atelier ou autre', max_length=200)),
                ('objet', models.CharField(help_text='Objet de la réunion', max_length=300)),
                ('nombre_participants', models.PositiveSmallIntegerField(default=1)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.sallereunion')),
            ],
            options={
                'verbose_name': 'Réservation de salle',
                'verbose_name_plural': 'Réservations de salles',
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='indisponibilite',
            name='salles',
            field=models.ManyToManyField(blank=True, related_name='indisponibilites', to='reservations.sallereunion'),
        ),
    ]
