# Generated by Django 6.0.3 on 2026-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_sallereunion_alter_reglerecurrence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='profanes_admis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sous_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('tbf', 'Tenue Blanche Fermée'), ('tbo', 'Tenue Blanche Ouverte'), ('funèbre', 'Funèbre')], default='standard', max_length=10),
        ),
    ]
