# Generated by Django 6.0.3 on 2026-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_profanes_admis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sous_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('tbf', 'Tenue Blanche Fermée'), ('tbo', 'Tenue Blanche Ouverte'), ('funebre', 'Funèbre')], default='standard', max_length=10),
        ),
    ]
