# Generated by Django 6.0.3 on 2026-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_sous_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sallereunion',
            name='type_salle',
            field=models.CharField(choices=[('reunion', 'Réunion'), ('cabinet_reflexion', 'Cabinet de réflexion'), ('agapes', 'Agapes')], default='reunion', max_length=20),
        ),
    ]
