# Generated by Django 6.0.3 on 2026-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_sallereunion_type_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cabinets',
            field=models.ManyToManyField(blank=True, related_name='reservations_cabinets', to='reservations.sallereunion'),
        ),
    ]
