# Generated by Django 6.0.3 on 2026-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_cabinets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsalle',
            name='nombre_cabinets',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 cabinet'), (2, '2 cabinets'), (3, '3 cabinets')], default=1),
        ),
    ]
