# Generated by Django 6.0.3 on 2026-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_demanderecurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandereglerecurrence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
