# Generated by Django 6.0.3 on 2026-04-06 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0006_loge_rite_precision'),
        ('reservations', '0012_reservationsalle_cabinet_prefere'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAccesPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_loge_libre', models.CharField(blank=True, help_text="Si la loge n'est pas dans la liste", max_length=200)),
                ('nom_venerable', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='attente', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_portail', to='loges.loge')),
            ],
            options={
                'verbose_name': "Demande d'accès portail",
                'verbose_name_plural': "Demandes d'accès portail",
                'ordering': ['-created_at'],
            },
        ),
    ]
