# Generated by Django 6.0.3 on 2026-04-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0006_loge_rite_precision'),
        ('reservations', '0016_reservation_type_congres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(help_text='Année de début de saison (ex. 2025 pour 2025-2026)')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('ouverte', 'Ouverte'), ('soumise', 'Soumise'), ('traitee', 'Traitée')], default='attente', max_length=10)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('commentaire_loge', models.TextField(blank=True)),
                ('loge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_saison', to='loges.loge')),
            ],
            options={
                'verbose_name': 'Validation de saison',
                'verbose_name_plural': 'Validations de saison',
                'ordering': ['annee', 'loge__nom'],
                'unique_together': {('loge', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ValidationSaisonLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('temple_nom', models.CharField(max_length=200)),
                ('avis', models.CharField(choices=[('ok', 'Confirmée'), ('deplacer', 'À déplacer'), ('annuler', 'À annuler')], default='ok', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_lignes', to='reservations.reglerecurrence')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reservations.validationsaison')),
            ],
            options={
                'verbose_name': 'Ligne de validation de saison',
                'verbose_name_plural': 'Lignes de validation de saison',
                'ordering': ['date'],
            },
        ),
    ]
