# Generated by Django 6.0.3 on 2026-04-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_validation_saison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationsaisonligne',
            name='avis',
            field=models.CharField(choices=[('attente', 'Non répondu'), ('ok', 'Confirmée'), ('deplacer', 'À déplacer'), ('annuler', 'À annuler')], default='attente', max_length=10),
        ),
    ]
