# Generated by Django 6.0.3 on 2026-06-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservationsalle_loge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Congrès : dernier jour. La facturation compte les jours du début à la fin.', null=True),
        ),
    ]
