# Generated by Django 6.0.3 on 2026-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_reservation_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglerecurrence',
            name='dates_exclues',
            field=models.JSONField(blank=True, default=list, help_text='Dates (ISO) déplacées/annulées exceptionnellement : la régénération ne recrée pas la tenue à ces dates.'),
        ),
    ]
