# Generated by Django 5.0.6 on 2026-08-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loges", "0011_loge_couverts_habituels"),
        ("reservations", "0021_reglerecurrence_dates_exclues"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsalle",
            name="group_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID partagé pour les réservations multi-salles créées en une seule opération",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RegleRecurrenceSalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour_semaine",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                (
                    "numero_semaine",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1re semaine"),
                            (2, "2e semaine"),
                            (3, "3e semaine"),
                            (4, "4e semaine"),
                            (-1, "Dernière semaine"),
                        ]
                    ),
                ),
                ("heure_debut", models.TimeField(default="19:30")),
                ("heure_fin", models.TimeField(default="22:30")),
                (
                    "mois_actifs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Mois actifs (1=Jan…12=Déc). Laisser vide = tous sauf juillet-août.",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "dates_exclues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dates ISO exclues (annulées/déplacées) — pas recréées à la régénération.",
                    ),
                ),
                (
                    "objet",
                    models.CharField(blank=True, default="Réunion", max_length=300),
                ),
                (
                    "nombre_participants",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = non renseigné"
                    ),
                ),
                (
                    "loge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_salle",
                        to="loges.loge",
                    ),
                ),
                (
                    "salles",
                    models.ManyToManyField(
                        help_text="Salles réservées à chaque occurrence (peut en inclure plusieurs)",
                        related_name="regles_recurrence",
                        to="reservations.sallereunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de récurrence salle",
                "verbose_name_plural": "Règles de récurrence salles",
            },
        ),
        migrations.AddField(
            model_name="reservationsalle",
            name="regle_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations_generees",
                to="reservations.reglerecurrencesalle",
            ),
        ),
    ]
