# Generated by Django 6.0.3 on 2026-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_reglerecurrence_dates_exclues'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('traite', 'Traité')], default='nouveau', max_length=10)),
                ('reponse', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('repondu_par', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
