# Generated by Django 5.0.6 on 2026-08-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0022_messagecontact"),
        (
            "reservations",
            "0022_reservationsalle_group_uuid_reglerecurrencesalle_and_more",
        ),
    ]

    operations = []
