# Generated by Django 5.0.6 on 2026-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0023_merge_20260804_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsalle",
            name="facturable",
            field=models.BooleanField(
                default=True,
                help_text="Cocher si cette réservation doit être facturée (à décocher pour les réunions internes non facturées)",
            ),
        ),
    ]
