# Generated by Django 5.0.6 on 2026-08-04 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loges", "0011_loge_couverts_habituels"),
        ("reservations", "0024_reservationsalle_facturable"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsalle",
            name="type_reunion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reunion", "Réunion de travail"),
                    ("chantier", "Chantier (apprentis / compagnons)"),
                    ("conseil", "Conseil d'officiers"),
                    ("banquet", "Banquet d'ordre"),
                    ("autre", "Autre"),
                ],
                default="reunion",
                help_text="Nature de la réunion (permet au traiteur d'anticiper les besoins)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DemandeRegleRecurrenceSalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "jour_semaine",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                (
                    "numero_semaine",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1re semaine"),
                            (2, "2e semaine"),
                            (3, "3e semaine"),
                            (4, "4e semaine"),
                            (-1, "Dernière semaine"),
                        ]
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("mois_actifs", models.JSONField(blank=True, default=list)),
                (
                    "objet",
                    models.CharField(blank=True, default="Réunion", max_length=300),
                ),
                ("nombre_participants", models.PositiveSmallIntegerField(default=0)),
                (
                    "type_reunion",
                    models.CharField(
                        choices=[
                            ("reunion", "Réunion de travail"),
                            ("chantier", "Chantier (apprentis / compagnons)"),
                            ("conseil", "Conseil d'officiers"),
                            ("banquet", "Banquet d'ordre"),
                            ("autre", "Autre"),
                        ],
                        default="reunion",
                        max_length=20,
                    ),
                ),
                ("nom_demandeur", models.CharField(max_length=100)),
                ("email_demandeur", models.EmailField(max_length=254)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                        ],
                        default="attente",
                        max_length=10,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("commentaire_admin", models.TextField(blank=True)),
                (
                    "loge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_regle_salle",
                        to="loges.loge",
                    ),
                ),
                (
                    "regle_creee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demande_source",
                        to="reservations.reglerecurrencesalle",
                    ),
                ),
                (
                    "salles",
                    models.ManyToManyField(
                        related_name="demandes_recurrence",
                        to="reservations.sallereunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de récurrence salle",
                "verbose_name_plural": "Demandes de récurrence salles",
                "ordering": ["-date_demande"],
            },
        ),
    ]
