# Generated by Django 5.0.6 on 2026-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0025_reservationsalle_type_reunion_demandereglerecsalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocagecreneaux",
            name="date_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin (optionnel)"
            ),
        ),
        migrations.AlterField(
            model_name="blocagecreneaux",
            name="date",
            field=models.DateField(verbose_name="Date de début"),
        ),
    ]
