from django.urls import path
from . import views
app_name = "administration"
urlpatterns = [
    path("", views.tableau_de_bord, name="tableau_de_bord"),
    path("valider/<int:pk>/", views.valider_reservation, name="valider_reservation"),
    path("valider-salle/<int:pk>/", views.valider_reservation_salle, name="valider_reservation_salle"),
    path("import/", views.import_excel, name="import_excel"),
    path("template-excel/", views.telecharger_template_excel, name="template_excel"),
    path("export-excel/", views.telecharger_export_excel, name="export_excel"),
    path("regles/", views.regles_liste, name="regles_liste"),
    path("regles/ajouter/", views.regle_form, name="regle_ajouter"),
    path("regles/<int:pk>/modifier/", views.regle_form, name="regle_modifier"),
    path("regles/<int:pk>/supprimer/", views.regle_supprimer, name="regle_supprimer"),
    path("regenerer/", views.regenerer_intelligent, name="regenerer"),
    path("reset/", views.reset_calendrier, name="reset_calendrier"),
    path("salles/", views.salles_liste, name="salles_liste"),
    path("salles/ajouter/", views.salle_form, name="salle_ajouter"),
    path("salles/<int:pk>/modifier/", views.salle_form, name="salle_modifier"),
    path("salles/<int:pk>/supprimer/", views.salle_supprimer, name="salle_supprimer"),
    path("parametres/", views.parametres, name="parametres"),
    path("parametres/test-smtp/", views.tester_smtp, name="tester_smtp"),
    path("agapes/", views.agapes_traiteur, name="agapes_traiteur"),
    path("agapes/export/", views.agapes_export_excel, name="agapes_export"),
    path("agapes/export/pdf/", views.agapes_export_pdf, name="agapes_export_pdf"),
    path("saison/", views.gestion_saison, name="gestion_saison"),
    path("saison/preview/excel/", views.preview_saison_excel, name="preview_saison_excel"),
    path("saison/preview/pdf/", views.preview_saison_pdf, name="preview_saison_pdf"),
    path("backup/", views.telecharger_backup, name="backup"),
    path("restaurer/", views.restaurer_backup, name="restaurer_backup"),
    path("portail/<int:pk>/valider/", views.valider_acces_portail, name="valider_acces_portail"),
    path("reservation-directe/", views.reservation_directe, name="reservation_directe"),
    path("saison/validation/", views.validation_saison_admin, name="validation_saison_admin"),
]
